vip-parsely: Fix return type for widget settings callback
The callback can return a bool value as well but triggers a fatal when that happens because we were enforcing it as an array.

```
Fatal error: Uncaught Error: Automattic\VIP\Parsely\Telemetry\track_widget_updated(): Return value must be of type array, bool returned
in /var/www/wp-content/mu-plugins/vip-parsely/Telemetry/Events/track-widget-updated.php on line 26
```