wp_handle_upload: Set default for context param
Some plugins (like `enable-media-replace`) call the action manually but don't pass the correct number of params (1 instead of 2), which can result in fatals:

```
Uncaught ArgumentCountError: Too few arguments to function Automattic\VIP\Stats\handle_file_upload(), 1 passed in /var/www/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected
```

Set a default to prevent those fatals.