Fix unit tests for WordPress nightly
The nightly version of WordPress requires yoast/phpunit-polyfills
to run unit tests.

Without the polyfills, it [throws an error](https://app.circleci.com/pipelines/github/Automattic/vip-go-mu-plugins/6933/workflows/92e8384c-31db-4547-afe6-ba550d8900a4/jobs/49746?invite=true#step-105-62)

Error: The PHPUnit Polyfills library is a requirement for running the WP test suite.

This commit adds the missing polyfill.